namespace: jborean93
name: test
version: 1.0.0
readme: README.md
authors:
  - Jordan Borean @jborean93
description: |
  Ansible publishing testing
license_file: COPYING
tags:
  - test
dependencies: {}
repository: https://github.com/foo
